### ISSUE TITLE
iOS work fine while Android Crash 

### ISSUE THREAD

**Issue by devdigitalappteam** [prscX/react-native-popover-menu#51]
java.lang.IllegalArgumentException: Section 'SectionHolder(title=Edit Profile, itemsHolderList=[])' has no items!
        at com.github.zawadz88.materialpopupmenu.MaterialPopupMenuBuilder$SectionHolder.convertToPopupMenuSection$material_popup_menu_release(MaterialPopupMenuBuilder.kt:134)
        at com.github.zawadz88.materialpopupmenu.MaterialPopupMenuBuilder.build(MaterialPopupMenuBuilder.kt:83)
        at ui.popovermenu.RNPopoverMenuModule$2.run(RNPopoverMenuModule.java:189)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by prscX** [comment]
Could you please share code snippet of the usage so that I can try the same.

Thanks
