### ISSUE TITLE
Could not find com.github.zawadz88.materialpopupmenu:material-popup-menu:4.1.0

### ISSUE THREAD

**Issue by darkbasic** [prscX/react-native-popover-menu#60]
It doesn't work with latest react-native on Android:

```
$ yarn android
yarn run v1.22.17
$ react-native run-android
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 880 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Installing the app...
Starting a Gradle Daemon, 1 busy and 3 incompatible Daemons could not be reused, use --status for details
> Task :app:mergeDebugAssets FAILED
14 actionable tasks: 14 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.zawadz88.materialpopupmenu:material-popup-menu:4.1.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - file:/home/niko/.m2/repository/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - file:/home/niko/devel/zg/zzg/node_modules/react-native/android/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - file:/home/niko/devel/zg/zzg/node_modules/jsc-android/dist/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - https://www.jitpack.io/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
     Required by:
         project :app > project :react-native-popover-menu

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugAssets'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not find com.github.zawadz88.materialpopupmenu:material-popup-menu:4.1.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - file:/home/niko/.m2/repository/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - file:/home/niko/devel/zg/zzg/node_modules/react-native/android/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - file:/home/niko/devel/zg/zzg/node_modules/jsc-android/dist/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - https://dl.google.com/dl/android/maven2/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
       - https://www.jitpack.io/com/github/zawadz88/materialpopupmenu/material-popup-menu/4.1.0/material-popup-menu-4.1.0.pom
     Required by:
         project :app > project :react-native-popover-menu

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

    at makeError (/home/niko/devel/zg/zzg/node_modules/execa/index.js:174:9)
    at /home/niko/devel/zg/zzg/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/home/niko/devel/zg/zzg/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:106:5)
    at async Command.handleAction (/home/niko/devel/zg/zzg/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I'm using `react-native-popover-menu@2.0.2`.

**Comment by hardibhalodiya** [comment]
I am also facing same issue, can anyone suggest solution for this.

**Comment by anhquan291** [comment]
I'm facing the same issue. Any helps please? Thanks a lot

**Comment by gdoudeng** [comment]
+1

**Comment by mucahittekin** [comment]
I suggested fix in #61 PR
